server:
  port: 9081
#spring:
#  datasource:
#    hikari:
#      minimum-idle: 5
#      idle-timeout: 600000
#      maximum-pool-size: 10
#      auto-commit: true
#      pool-name: HikariCorePool
#      max-lifetime: 1800000
#      connection-timeout: 30000
#    url: jdbc:postgresql://localhost:5432/mydb
#    username: mkyong
#    password: password
#    jpa:
#      hibernate:
#        ddl-auto: create-drop
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#app:
#  db:
#    init:
#      enabled: true

